version: "3.9"
services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=lab_manager
      - MYSQL_USER=lab_manager
      - MYSQL_PASSWORD=superStrongPassword
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default

  esearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - default

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - esearch
      - db
    networks:
      - default
    ports:
      - "5000:5000"    
    environment:
      FLASK_ENV: production
      DB_USER: lab_manager
      DB_PASSWORD: superStrongPassword 
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: lab_manager
      ELASTICSEARCH_URL: http://elasticsearch:9200

volumes:
  db: