"""empty message

Revision ID: 492ce634aec8
Revises: 
Create Date: 2022-02-22 19:47:03.540253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492ce634aec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('biometry', sa.Boolean(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('grr', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('grr')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
