"""Add Reserved project Field

Revision ID: 63664a412022
Revises: e512b4edec0e
Create Date: 2022-04-11 16:38:38.871780

"""
from alembic import op
import sqlalchemy as sa

from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, DateTime, Boolean
from lab_manager.models import User

# revision identifiers, used by Alembic.
revision = '63664a412022'
down_revision = 'e512b4edec0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('reserved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

    # Create an ad-hoc table to use for the insert statement.

    project_table = table('project',
        column('id', Integer),
        column('name', String),
        #column('date_created', DateTime),
        column('active', Boolean),
        column('reserved', Boolean)
    )

    op.bulk_insert(project_table,
        [
            {'id':1, 'name':'Admin',
                    #'date_created':date(),
                    'active':True,
                    'reserved':True
            }
        ]
    )

    user_table = table('user',
        column('id', Integer),
        column('name', String),
        column('email', String),
        column('password', String),
        #column('date_created', DateTime),
        column('biometry', Boolean),
        column('project', Integer),
        column('grr', Integer),
        column('course', String),
        column('approved_by', Integer),
        #column('date_approved', DateTime),
        column('approved', Boolean),
        column('admin', Boolean),
    )

    

    op.bulk_insert(user_table,
        [
            {
                'id':1, 
                'name':'Admin',
                'email':'admin@admin.com',
                'password':User.create_password('SuperAdmin123'),
                #'date_created':date,
                'biometry':False,
                'project':1,
                'grr':0000000,
                'course':'Mechanical Engineering',
                'approved_by':'0',
                #'date_approved': date,
                'approved':False,
                'admin': True
            }
        ]
    )    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! 
    op.drop_column('project', 'reserved')
    # ### end Alembic commands 
