"""SEED Admin

Revision ID: 869cac3c099f
Revises: 63664a412022
Create Date: 2022-04-11 19:22:20.384306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '869cac3c099f'
down_revision = '63664a412022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'project',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'project',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
