-- MySQL Script generated by MySQL Workbench
-- dom 10 abr 2022 19:00:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab_manager` ;
USE `lab_manager` ;

-- -----------------------------------------------------
-- Table `lab_manager`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_manager`.`project` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `date_created` DATETIME NULL,
  `active` TINYINT NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_user1_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `lab_manager`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_manager`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_manager`.`user` (
  `id` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `name` VARCHAR(150) NULL,
  `password` VARCHAR(128) NULL,
  `date_created` DATETIME NOT NULL,
  `biometry` TINYINT NOT NULL,
  `course` VARCHAR(50) NULL,
  `approved_by` INT NULL,
  `date_approved` DATETIME NULL,
  `approved` TINYINT NOT NULL,
  `admin` VARCHAR(45) NOT NULL,
  `project` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_project_idx` (`project` ASC) VISIBLE,
  CONSTRAINT `fk_user_project`
    FOREIGN KEY (`project`)
    REFERENCES `lab_manager`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_manager`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_manager`.`post` (
  `id` INT NOT NULL,
  `text` TEXT(500) NOT NULL,
  `date_created` DATETIME NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user1_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`author`)
    REFERENCES `lab_manager`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_manager`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_manager`.`comment` (
  `id` INT NOT NULL,
  `text` TEXT(300) NOT NULL,
  `date_created` DATETIME NULL,
  `author` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`author` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`author`)
    REFERENCES `lab_manager`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `lab_manager`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
